import {  SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import { api } from "~/utils/api";

export default function Home() {
  const {data} = api.post.getAllUser.useQuery()
  console.log(data)
  const users = useUser()
  console.log(users, "some")
  return (
    <>
    <Head>
      <title>Dashboard</title>
      <meta name="Dashboard" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
        <SignOutButton>
          <button>Sign Out</button>
        </SignOutButton>
    </main>
    </>
  );
}
