import {  SignOutButton } from "@clerk/nextjs";
import { Button, Modal } from "antd";
import Head from "next/head";
import { useState } from "react";
import { api } from "~/utils/api";
import AddConsumerForm from "../components/addConsumerForm";

export default function Home() {
  const [modalIsOpen, setModalIsOpen] = useState(false)
  const {data} = api.post.getAllUser.useQuery()
  console.log(data)

  const openModal = () => {
    setModalIsOpen(true)
  }
  const handleCancel = () => {
    setModalIsOpen(false)
  }

  return (
    <>
      <Head>
        <title>Consumers</title>
        <meta name="Consumers" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex  h-full ">
        <Button onClick={openModal}>Add Consumer</Button>
        <Modal 
        open={modalIsOpen}
        title="Add Consumer"
        footer={null}
        // onOk={handleOk}
        // confirmLoading={confirmLoading}
        onCancel={handleCancel}
        >
          <AddConsumerForm/>
        </Modal>
      </main>
    </>
  );
}